apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-limitrange-customizer-admission-manager
  labels:
    app: quota-limitrange-customizer-customizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quota-limitrange-customizer-customizer
  template:
    metadata:
      labels:
        app: quota-limitrange-customizer-customizer
    spec:
      serviceAccount: quota-limitrange-customizer-admission-manager-sa
      containers:
        - name: quota-limitrange-customizer-customizer
          env:
            - name: ADD_SECURITRYCONEXT_PER_POD
              value: "false"
          image: daocloud.io/daocloud/cdp-limitrange-customizer:latest
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/tls.crt
            - -tlsKeyFile=/etc/webhook/certs/tls.key
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: quota-limitrange-customizer-admission-manager-certs
      ## By DaoCloud
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      ##
