apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-webhook-quota-limitrange-customizer-customizer-cfg
  annotations:
    cert-manager.io/inject-ca-from: cdp-customizer/quota-limitrange-webhook-cert
  labels:
    app: quota-limitrange-customizer-customizer
webhooks:
  - name: validate-quota-limitrange-customizer-console.datacreating.com
    clientConfig:
      service:
        name: quota-limitrange-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["limitranges","resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: monitoring-platform-access
          operator: Exists
    timeoutSeconds: 5
  - name: validate-quota-limitrange-customizer-cml.datacreating.com
    clientConfig:
      service:
        name: quota-limitrange-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["limitranges","resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: associatedCRP
          operator: Exists
    timeoutSeconds: 5
  - name: validate-quota-limitrange-customizer-implala.datacreating.com
    clientConfig:
      service:
        name: quota-limitrange-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["limitranges","resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: istio-injection
          operator: Exists
    timeoutSeconds: 5
  - name: validate-quota-limitrange-customizer-monitoring.datacreating.com
    clientConfig:
      service:
        name: quota-limitrange-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["limitranges","resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: cdp.cloudera/version
          operator: Exists
    timeoutSeconds: 5
  - name: validate-quota-limitrange-ds-parent-namespace.datacreating.com
    clientConfig:
      service:
        name: quota-limitrange-admission-manager
        namespace: cdp-customizer
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["limitranges","resourcequotas"]
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: ds-parent-namespace
          operator: Exists
    timeoutSeconds: 5